# Generated by Django 4.2.1 on 2023-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_employee_work_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
